### PR TITLE
Std bytes buffer

### PR DESCRIPTION
**Pull request by kshvakov**
Please use std bytes.Buffer

thank you

### CODE REVIEW

**Comment by vavrusa** [comment]
I'm going to test 34075cb (hope the allocations don't escape), but c3d55a8 has a significant performance regression (~30% less on our write throughput) so I'm reluctant to change it.

The reason is that you don't want additional dependency? Having chunked buffer and avoiding the copies make sense to me.

**Comment by vavrusa** [comment]
It indeed escapes:

```
write.go:163: make([]byte, 4) escapes to heap
write.go:178: make([]byte, 8) escapes to heap
write.go:189: []byte literal escapes to heap
write.go:191: []byte literal escapes to heap
write.go:193: []byte literal escapes to heap
write.go:198: make([]byte, 2) escapes to heap
write.go:213: make([]byte, 4) escapes to heap
write.go:228: make([]byte, 8) escapes to heap
```

It's better than the previous version, but still ~10% less throughput.

**Comment by vavrusa** [comment]
I've rebased to upstream master

**Comment by kshvakov** [comment]
yes, i don't want additional dependency. i will write custom buffer in the coming days

thank you

**Comment by vavrusa** [comment]
Understandable, thank you for writing the library!

**Pull request closed without merging**
